### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [poabor/Block4#11]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by poabor** [comment]
Полушкину Александру.
poabor@gmail.com

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by poabor** [comment]
Пришло
