### ISSUE TITLE
Продажа товара

### ISSUE THREAD

**Issue by poabor** [poabor/Block4#2]
Создать документ "Продажа" для фиксации факта продажи товара.

**Comment by alehinsasha** [comment]
Уточните, пожалуйста, с чем испытываете затруднение?

**Comment by poabor** [comment]
Считается ли [такой вариант](https://github.com/poabor/Block4/commit/91fc1bf02a68397d9247ffbc9f85e13ac0a5cdc9) решением по проверке не проведения документа при нехватке остатков на складе?
Или как-то по другому проходит проверка такой ситуации? Насколько я понял, behavior считает все ок, если нет исключений.

**Comment by alehinsasha** [comment]
Я прокомментировал коммит, заметили?

**Comment by poabor** [comment]
да, спасибо большое.
