### ISSUE TITLE
Разработка по промышленны

### ISSUE THREAD

**Issue by alehinsasha** [poabor/Block4#8]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by poabor** [comment]
В этом [модуле](https://github.com/poabor/Block4/blob/master/src/features/step_definitions/%D0%9F%D1%80%D0%BE%D0%B4%D0%B0%D0%B6%D0%B0%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D0%B0/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl) реализована загрузка фикстур.

**Comment by alehinsasha** [comment]
Например, есть две фичи, одна проверяет продажу другая покупку. В обоих фичах нужно подготавливать инфобазу (напоминаю: сценарий сам для себя готовит окружение). Нужно создать третью фичу и положить ее в отдельный каталог в \features. На практике, в таких библиотечных фичах накапливаются шаги которые используются в других фичах. Предлагаю реализвать универсальный (параметризованный) шаг удаление всех элементов справоника и использовать этот шаг в фичах покупки и продажи.

**Comment by poabor** [comment]
Реализовал шаг удаления элементов

**Comment by alehinsasha** [comment]
готово
