### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [poabor/Block4#9]
- [x] Один шаг обрабатывающий справочник

**Comment by poabor** [comment]
Александр, не понял, что нужно сделать в этой задаче?

**Comment by alehinsasha** [comment]
Нужно создать фичу с одним сценарием и одним шагом, но контекст может быть (для подключения клиента тестирования). В процедуре проверки шага используя свойство "ТестовоеПриложение" переменной "КонтекстСохраняемы" нужно воспроизвести следующие действия пользователя: открыть форму списка справочника → добавить новый элемент → указать наименование → записать и закрыть новый элемент → закрыть форму списка.

**Comment by alehinsasha** [comment]
готово
